<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $produk = [
            // 4 produk
            [
                'nama_produk' => 'Hugo F-HU 1388 003 55',
                'merek' => 'Hugo',
                'tipe_produk' => 'F-HU 1388 003 55',
                'harga_produk' => 500000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Pria',
                'warna' => 'Hitam',
                'material' => 'Metal',
                'bentuk' => 'Aviator',
                'bridge' => '18',
                'diagonal' => '51',
                'ukuran' => '55',
                'gambar' => 'hu-1388-003-55.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Giordano F-GD-GA03452 05 53',
                'merek' => 'Giordano',
                'tipe_produk' => 'F-GD-GA03452 05 53',
                'harga_produk' => 750000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Unisex',
                'warna' => 'Transparan',
                'material' => 'Metal',
                'bentuk' => 'Browline',
                'bridge' => '19',
                'diagonal' => '53',
                'ukuran' => '53',
                'gambar' => 'gd-ga03452-05-53.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Giordano F-GD-GA02971 03 55',
                'merek' => 'Giordano',
                'tipe_produk' => 'F-GD-GA02971 03 55',
                'harga_produk' => 850000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Unisex',
                'warna' => 'Putih',
                'material' => 'Plastic',
                'bentuk' => 'Square',
                'bridge' => '17',
                'diagonal' => '55',
                'ukuran' => '55',
                'gambar' => 'gd-ga02971-03-55.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Qina F-QI QA7010 B30 51',
                'merek' => 'Qina',
                'tipe_produk' => 'F-QI QA7010 B30 51',
                'harga_produk' => 450000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Rose Gold',
                'material' => 'Titanium',
                'bentuk' => 'Oval',
                'bridge' => '20',
                'diagonal' => '51',
                'ukuran' => '51',
                'gambar' => 'qi-qa7010-b30-51.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4 produk baru
            [
                'nama_produk' => 'Chopard F-CR-VCH358 0703 59',
                'merek' => 'Chopard',
                'tipe_produk' => 'F-CR-VCH358 0703 59',
                'harga_produk' => 1200000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Pria',
                'warna' => 'Hitam',
                'material' => 'Rubber',
                'bentuk' => 'Rectangle',
                'bridge' => '19',
                'diagonal' => '59',
                'ukuran' => '59',
                'gambar' => 'F CR VCH358 0703 59.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Illustro F-IS-DCWP201 C2 50',
                'merek' => 'Illustro',
                'tipe_produk' => 'F-IS-DCWP201 C2 50',
                'harga_produk' => 950000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Pria',
                'warna' => 'Hitam',
                'material' => 'Wood',
                'bentuk' => 'Round',
                'bridge' => '18',
                'diagonal' => '50',
                'ukuran' => '50',
                'gambar' => 'F IS DCWP201 C2 50.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Gucci F-GU-K-2049O 004 57',
                'merek' => 'Gucci',
                'tipe_produk' => 'F-GU-K-2049O 004 57',
                'harga_produk' => 2500000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Gold',
                'material' => 'Metal',
                'bentuk' => 'Cat Eye',
                'bridge' => '17',
                'diagonal' => '57',
                'ukuran' => '57',
                'gambar' => 'F GU K 2049O 004 57.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Guy Laroche F-GL-2412 C5 54',
                'merek' => 'Guy Laroche',
                'tipe_produk' => 'F-GL-2412 C5 54',
                'harga_produk' => 650000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Pria',
                'warna' => 'Black',
                'material' => 'Plastic',
                'bentuk' => 'Flat Top',
                'bridge' => '18',
                'diagonal' => '54',
                'ukuran' => '54',
                'gambar' => 'F GL 2412 C5 54.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4 produk baru
            [
                'nama_produk' => 'Beneton F-BE-3101 1-884 52',
                'merek' => 'Beneton',
                'tipe_produk' => 'F-BE-3101 1-884 52',
                'harga_produk' => 550000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Pink',
                'material' => 'Metal',
                'bentuk' => 'Round',
                'bridge' => '16',
                'diagonal' => '52',
                'ukuran' => '52',
                'gambar' => 'F BE 3101-1 884 52.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Nike F-NK-7403LB 410 56',
                'merek' => 'Nike',
                'tipe_produk' => 'F-NK-7403LB 410 56',
                'harga_produk' => 800000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Unisex',
                'warna' => 'Biru',
                'material' => 'Plastic',
                'bentuk' => 'Rectangle',
                'bridge' => '18',
                'diagonal' => '56',
                'ukuran' => '56',
                'gambar' => 'F NK 7403LB 410 56.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Ted Baker F-TR-2367 1-739 53',
                'merek' => 'Ted Baker',
                'tipe_produk' => 'F-TR-2367 1-739 53',
                'harga_produk' => 1100000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Merah',
                'material' => 'Plastic',
                'bentuk' => 'Rectangle',
                'bridge' => '17',
                'diagonal' => '53',
                'ukuran' => '53',
                'gambar' => 'F TR 2367-1 739 53.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Hindar F-H5-FMDP2970B GRN 250',
                'merek' => 'Hindar',
                'tipe_produk' => 'F-H5-FMDP2970B GRN 250',
                'harga_produk' => 350000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Unisex',
                'warna' => 'Hijau',
                'material' => 'Plastic',
                'bentuk' => 'Rectangle',
                'bridge' => '20',
                'diagonal' => '50',
                'ukuran' => '250',
                'gambar' => 'F H5 FMDP2970B GRN 250.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4 produk baru - Virtus, Puma, Bolon
            [
                'nama_produk' => 'Virtus F-VE-SPD-6833 C2 47',
                'merek' => 'Virtus',
                'tipe_produk' => 'F-VE-SPD-6833 C2 47',
                'harga_produk' => 600000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Unisex',
                'warna' => 'Kuning',
                'material' => 'Plastic',
                'bentuk' => 'Geometric',
                'bridge' => '18',
                'diagonal' => '47',
                'ukuran' => '47',
                'gambar' => 'F VE SPD-6833 C2 47.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Puma F-PX-PJ0085O 005 48',
                'merek' => 'Puma',
                'tipe_produk' => 'F-PX-PJ0085O 005 48',
                'harga_produk' => 550000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Ungu',
                'material' => 'Plastic',
                'bentuk' => 'Rectangle',
                'bridge' => '17',
                'diagonal' => '48',
                'ukuran' => '48',
                'gambar' => 'F PX PJ0085O 005 48.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Bolon F-BN-BJ3219 B20 52',
                'merek' => 'Bolon',
                'tipe_produk' => 'F-BN-BJ3219 B20 52',
                'harga_produk' => 700000,
                'stok' => rand(1, 4),
                'jenis_kelamin' => 'Wanita',
                'warna' => 'Tortoise',
                'material' => 'Plastic',
                'bentuk' => 'Cat Eye',
                'bridge' => '18',
                'diagonal' => '52',
                'ukuran' => '52',
                'gambar' => 'F BN BJ3219 B20 52.png',
                'status_produk' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('produk')->insert($produk);
    }
}